#KubeJS Common Properties
#Mon Aug 04 18:44:27 CST 2025
allowAsyncStreams=true
announceReload=true
creativeModeTabIcon=minecraft\:purple_dye
hideServerScriptErrors=false
ignoreCustomUniqueRecipeIds=false
matchJsonRecipes=true
packmode=
saveDevPropertiesInConfig=false
serverOnly=false
startupErrorGUI=true
startupErrorReportUrl=
